### ISSUE TITLE
`npm run dev` results in "Could not resolve entry module (undefined\server.ts)."

### ISSUE THREAD

**Issue by regnaio** [babichjacob/sapper-typescript-graphql-template#14]
Git cloned latest master (22a2cced9ffaa167351f7f7dca3b612a1126122d)

Ran `npm i` followed by `npm run dev`

Received error: "Could not resolve entry module (undefined\server.ts)."

For reference:
$ npm -v
6.14.7
$ node -v
v14.8.0

Log:
$ npm run dev

> sapper-typescript-graphql-template@2020.8.13 dev C:\dev\sapper-typescript-graphql-template
> run-p validate:dev sapper:dev

> sapper-typescript-graphql-template@2020.8.13 validate:dev C:\dev\sapper-typescript-graphql-template
> svelte-check --ignore src/node_modules/@sapper --watch

> sapper-typescript-graphql-template@2020.8.13 sapper:dev C:\dev\sapper-typescript-graphql-template
> sapper dev

Loading svelte-check in workspace: c:\dev\sapper-typescript-graphql-template
Getting Svelte diagnostics...
====================================

====================================
svelte-check found no errors and no warnings
✗ client
Could not resolve entry module (undefined\client.ts).
(node:19904) UnhandledPromiseRejectionWarning: Error: Could not find chunk that owns index.svelte
    at C:\dev\sapper\dist\create_manifest_data.js:319:19
    at Array.forEach (<anonymous>)
    at extract_css (C:\dev\sapper\dist\create_manifest_data.js:314:16)
    at RollupResult.to_json (C:\dev\sapper\dist\create_manifest_data.js:458:18)
    at handle_result (C:\dev\sapper\dist\dev.js:272:55)
    at C:\dev\sapper\dist\dev.js:356:17
    at WatchEmitter.<anonymous> (C:\dev\sapper\dist\create_manifest_data.js:590:37)
    at WatchEmitter.emit (events.js:314:20)
    at Watcher.emit (C:\dev\sapper-typescript-graphql-template\node_modules\rollup\dist\shared\watch.js:611:22)
    at Watcher.run (C:\dev\sapper-typescript-graphql-template\node_modules\rollup\dist\shared\watch.js:649:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19904) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✗ server
Could not resolve entry module (undefined\server.ts).

**Comment by babichjacob** [comment]
Thanks for the reproduction steps! I've just tried this (in a fresh clone, not the original folder I already work in) and cannot reproduce on macOS with Node 14.5.0 and npm 6.14.5.

This may be a Windows-only issue. Let me find an upstream issue.

**Comment by babichjacob** [comment]
Not Windows-only actually, since here's one issue on Windows:
https://github.com/sveltejs/sapper/issues/1334

and one on macOS:
https://github.com/sveltejs/sapper/issues/1396

I also have a Windows machine I can test on but it's being used at the moment, so I'm not sure if I can get to that tonight.

**Comment by regnaio** [comment]
Thank you, @babichjacob! Indeed, currently on Windows 10

**Comment by babichjacob** [comment]
Is that a global installation of `sapper` or a fork being used with `npm link`, for instance?

**Comment by babichjacob** [comment]
> Is that a global installation of `sapper` or a fork being used with `npm link`, for instance?

I'm still suspicious of this being the problem, seeing as the path to the file(s) the error is originating from is in `C:\dev\sapper` rather than in `C:\dev\sapper-typescript-graphql-template\node_modules`.

I downloaded the repository on Windows 10 last night and it just worked:tm:, but I still wasn't able to reproduce your error by downgrading to older versions of Sapper (0.27.10, for instance).

**Comment by maddalax** [comment]
I am also getting this error when I upgraded my project (cloned when sapper was on 0.28.2), to sapper 0.28.3.

It seems to work on a fresh clone from master of the template.

I tried to copy over tsconfig, rollup config, package.json versions, but I am still unable to get it working on my project after upgrading to sapper 0.28.3, worked perfectly on 0.28.2.

**Comment by maddalax** [comment]
So this seems to also happen on mac os x as well for me. Possibly might be related to using node_path with rollup node resolver

```
	customResolveOptions: {
			paths: process.env.NODE_PATH.split(/[;:]/),
	},
```

The error goes away and it builds if I remove this, but it is unable to find my imports.

**Comment by babichjacob** [comment]
How're things on 0.28.6? Perhaps after rebasing from this template again with the two newest commits from today?

**Comment by babichjacob** [comment]
There hasn't been any activity on this for so long.
