### ISSUE TITLE
vs code linter shows typescript errors like "Type annotations can only be used in TypeScript files"

### ISSUE THREAD

**Issue by Choongkyu** [babichjacob/sapper-typescript-graphql-template#21]
hello. thanks for building this template. I'm currently seeing an issue like in `ExampleComponent.svelte` where any sort of type annotations issues an error `Type annotations can only be used in TypeScript files`.  I was wondering how I might be able to resolve this.  thanks!

**Comment by babichjacob** [comment]
Is this in the latest clone of the template?

**Comment by babichjacob** [comment]
I see these messages on a fresh clone too. It was solved for me by running `npm install` (or your package manager's installation command like `yarn` or `pnpm install`). Then I typed/backspaced in the file with the errors and they went away.

Does that work for you?

**Comment by babichjacob** [comment]
There hasn't been any activity on this in so long.
